### ISSUE TITLE
I can't download the sound files no matter how long I wait.

### ISSUE THREAD

**Issue by Tomo-Tg** [Qrael/PjskSUSPatcher#1]
I can download old songs like 「ハッピーシンセサイザ」, but I can't download recently added songs like 「What's up? Pop!」 because the media conversion is not finished even after waiting for a day.
Can you please fix this problem?

**Comment by Tomo-Tg** [comment]
I found the cause a little more precisely, I looked at the song database in pjsek.ai and found that the song data after VS_0302_01 consists of .acb files, not .flac.
Is it possible to update the patcher to support .acb files as well?

**Comment by Zokhoi** [comment]
I added [a commit](https://github.com/Qrael/PjskSUSPatcher/commit/3af3648413709129bdbdc8a881cd6c9c9f5fe7cb) to try fallback links but we'll still have to wait until the asset source providers whom I have already contacted fixes their side.

**Comment by Tomo-Tg** [comment]
Understood, thank you for the update.

**Comment by Zokhoi** [comment]
It should be fine now.

**Comment by Tomo-Tg** [comment]
Yes, it appears so.
Thank you very much, it has come in very handy.
