### ISSUE TITLE
tool stuck at retrieving song list for 2 hours

### ISSUE THREAD

**Issue by karywina** [Qrael/PjskSUSPatcher#5]
Hi, I saw this tool on reddit yesterday because i had literally no charts in umiguri so i decided to give it a shot today. I've been weirded out that the site is stuck on retrieving song list so i just went and did something for 2 hours, I come back and its still loading. Is this a common issue?

**Comment by karywina** [comment]
![image](https://github.com/user-attachments/assets/9410eb70-a45e-4be1-b71c-e4dadb75bfb6)

**Comment by Zokhoi** [comment]
It seems that the api provider has suspended their service. I will work on using another source for the song list.

**Comment by Zokhoi** [comment]
The site should be fixed now, please test and see if there are any other issues.
